### ISSUE TITLE
Segmentation fault in lighttable view

### ISSUE THREAD

**Issue by ilveroluca** [darktable-org/darktable#17382]
### Describe the bug

In lighttable view, darktable loads the last collection the last correction I successfully worked on.  I then choose a different, old collection (2013) and darktable segfaults as it loads the image previews.

### Steps to reproduce

1. Open darktable
2. Change film roll
3. Wait while thumbnails load

### Expected behavior

darktable should load previews without segfaulting

### Logfile | Screenshot | Screencast

[darktable-no-opencl.stdout.log](https://github.com/user-attachments/files/16765379/darktable-no-opencl.stdout.log)
[darktable-no-opencl.stderr.log](https://github.com/user-attachments/files/16765383/darktable-no-opencl.stderr.log)

### Where did you obtain darktable from?

OBS

### darktable version

4.8.1

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 24.04 LTS

### Describe your system?

Kubuntu 24.04 desktop, 16 GB RAM.

```
17:54 [luca@box ~] inxi -G
Graphics:
  Device-1: NVIDIA TU116 [GeForce GTX 1660 SUPER] driver: nvidia v: 550.90.07
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.6 driver: X:
    loaded: modesetting,nouveau,nvidia unloaded: fbdev,vesa
    gpu: nvidia,nvidia-nvswitch resolution: 1: 2560x1440~60Hz 2: N/A
```

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce GTX 1660 SUPER, 6 GB, Nvidia Driver Version: 550.90.07

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Tested with `--disable-opencl`: did not affect result.

I have found a specific image that triggers the issue.  I can share the XMP and ORF (privately) if that can help debug the issue.

I have previously experienced a similar problem, which I reported in #17139; the fix to that problem should be in the version of darktable I'm using though.
