### ISSUE TITLE
Automatic WinGet publishing of nightly tag?

### ISSUE THREAD

**Issue by maxbengtzen** [darktable-org/darktable#18403]
**Is your feature request related to a problem? Please describe.**

Not a problem with the app itself. But the distribution of Windows Nightly builds could be more simple, I guess? Today, only the stable releases are published to WinGet. It would be a dream to be able to keep the nightly version updated just as easily.

**Describe the solution you'd like**

I would like an automated action for publishing Winget Packages for the nightly version of the Windows release to the WinGet repo. I haven't used it myself, but this action - [WinGet Releaser (Github Action)](https://github.com/marketplace/actions/winget-releaser) - in marketplace looks promising. From what I can read, I guess you manually create the first Nightly manifest and then the action can fetch future information from that manifest and update with the release info.

```
name: Publish Darktable Nightly to WinGet
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Get version
        id: get-version
        run: |
          # Finding the version from release name
          $VERSION="${{ github.event.release.name }}" -replace '^.*/ '
          "version=$VERSION" >> $env:GITHUB_OUTPUT
        shell: pwsh
      - name: Publish Darktable Nightly to WinGet
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: Darktable.Darktable.Nightly
          installers-regex: '\.exe$' # Only .exe files
          version: ${{ steps.get-version.outputs.version }}
          token: ${{ secrets.WINGET_TOKEN }}
```

**Alternatives**

**Additional context**

 I have seen projects such as [GIMP](https://github.com/microsoft/winget-pkgs/tree/master/manifests/g/GIMP/GIMP/Nightly) and [Brave](https://github.com/microsoft/winget-pkgs/tree/master/manifests/b/Brave/Brave/Nightly) do the same thing. Might be something to benchmark and/or inspect.

![Image](https://github.com/user-attachments/assets/f3a4d7fc-9358-44a8-990c-bd1b6e69eb5c)
